### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3' in file exec.py on line 22

### ISSUE THREAD

**Issue by JoaoMarra** [thiagosantos/bradesco-cnab240#1]
Estou tentando rodar o codigo e recebo esse erro.

e não faço ideia como deve ser as entradas do programa, teria como explicar por favor?

**Comment by thiagosantos** [comment]
@JoaoMarra você está usando o Python3?
É necessário.

**Para usar o projeto você precisa seguir esses passos:**

1 - Dentro do projeto existe a pasta [cnab240/confs](https://github.com/thiagosantos/bradesco-cnab240/tree/master/cnab240/confs) lá você duplica o arquivo de exemplo para criar a configuração da sua empresa, altera o nome sem usar espaços, algo como "minhaempresa.conf" ao invés de "minha empresa.conf".

2 - Criar um arquivo de entrada CSV (delimitando por ;) no padrão a seguir:
banco
agencia
agencia digito verificador
conta
conta digito verificador
nome do favorecido
valor do pagamento em centavos
data para o pagamento
cpf

ex: 
> 237;3002;3;000000;3;MEU LINDO NOME;100050;26092018;00000000000
> 237;3002;3;000001;2;NOME MEU LINDO;200050;26092018;00000000000
Cada linha um funcionário

3 - Com a configuração criada você pode executar o exec.py passando alguns parametros
_-c_ é o seu arquivo de configuração ( ex: minhaempresa )
_-a_ é o arquivo de entrada
_-d_ é o driver que vai processar o arquivo de entrada (padrão CSV)

Como, por enquanto, só temos o driver CSV ele é o padrão, então não precisa usar o parametro -d

`>python3 ./exec.py -c minhaempresa -a /var/saida/meuarquivo.csv
`

A saida é um arquivo CNAB240 no padrão do Bradesco.
Faz um novo pull que subi o driver CSV.
