### ISSUE TITLE
Funcionar em outros bancos

### ISSUE THREAD

**Issue by gusleig** [thiagosantos/bradesco-cnab240#2]
Thiago desculpe falar por aqui, mas era a única forma que encontrei.
Sabe se o mesmo código vai funcionar em outros bancos, em especial o banco Inter que estava precisando.

Obrigado e parabéns pelo trabalho!

**Comment by thiagosantos** [comment]
O layout cnab 240 é um padrão da FEBRABAN. Acredito que funcione sim, mas talvez seja necessário algumas alterações. 

Você tem o layout do arquivo de remessa fornecido pelo banco inter?

**Comment by gusleig** [comment]
Não tenho do inter, ja procurei na internet, site deles, nada... só se ligar lá... nunca vi tanto segredo....

**Comment by thiagosantos** [comment]
Procurei e também não achei, mas o como o layout é padrão acredito que funcione se fizer algumas alterações.

Se você estiver disposto a testar o arquivo de saída da folha no banco inter, eu estou disposto a fazer as alterações nesse código para adaptar para ele e possivelmente para outros bancos também.

**Comment by gusleig** [comment]
Eu testaria com toda certeza, o que você precisa?

**Comment by thiagosantos** [comment]
A princípio nada demais, clona o repositório, no arquivo de [configuração](https://github.com/thiagosantos/bradesco-cnab240/blob/master/cnab240/confs/exemplo.conf) cria um para você com o banco sendo 077 (banco inter) e o nome do banco sendo "BANCO INTER".  

`{
"banco" : "077",
"nome_banco" :"BANCO INTER" ....}`

Gera um arquivo [csv](https://github.com/thiagosantos/bradesco-cnab240/blob/master/tmp/funcionarios.csv) com uma linha só de teste para pagamento, [o layout do csv está aqui ](https://github.com/thiagosantos/bradesco-cnab240#csv). Coloca o valor de R$ 1,00 (100) para fazer o teste, põe os seus dados para o valor cair na sua conta, e por último roda o [script](https://github.com/thiagosantos/bradesco-cnab240#utiliza%C3%A7%C3%A3o) e sobe lá no banco inter.

Se o banco inter aceitar e o pagamento cair certinho eu altero a documentação dizendo que há tb suporte para o banco inter, se der erro vc cola aqui e faço os ajustes que forem necessários!

**Comment by gusleig** [comment]
Fiz o teste, deu erro quando fui subir o arquivo, a página do Inter reclamou de data de debito e data de credito. Estou ligando pra eles pra ver se existe algum manual. Depois te falo.

**Comment by thiagosantos** [comment]
Interessante.
Qual a data de pagamento que você colocou dentro do arquivo csv?

> 237;0279;8;099999;2;THIAGO SALARIO MINIMO 1;104500;**03052019**;22222222222


Se você tentou para pagamento hoje (D+0), tenta para pagamento amanhã (D+1).

**Comment by gusleig** [comment]
Recebi o formato deles, realmente parece diferente do que o programa gera em pequenos detalhes, olha so..

[Folha CNAB 240 - Exemplo.txt](https://github.com/thiagosantos/bradesco-cnab240/files/5299431/Folha.CNAB.240.-.Exemplo.txt)

**Comment by thiagosantos** [comment]
Mandou muito bem!
O que você notou de diferente?


> Recebi o formato deles, realmente parece diferente do que o programa gera em pequenos detalhes, olha so..
> 
> [Folha CNAB 240 - Exemplo.txt](https://github.com/thiagosantos/bradesco-cnab240/files/5299431/Folha.CNAB.240.-.Exemplo.txt)

**Comment by gusleig** [comment]
Então, tem que parametrizar mais, algumas configurações dos headers estão hard coded, teria que pegar as informações do arquivo de configuração e colocar nas funções de header pra puxar o código do banco correto.

Outra diferença que notei é que no header do lote, o endereço que eles colocam não tem bairro, o que deixa a linha mais curta.

Também nessa linha, posição 155 eles colocam a data do pagamento, o que no seu programa está 0000000000

0770001300001A0000000770000190000006501601 NOME COLABORADOR                                  10032017BRL000000000000000000000000000100                    10032017000000000000100                                                    0

**Comment by thiagosantos** [comment]
Achei pouca coisa, acho que rola fazer funcionar no Banco Inter!
Estou analizando o txt que você me mandou com um que eu tenho aqui e os dados estão batendo, mas estou comparando Bradesco com Inter. Vou fazer um config só para o banco inter e fazer alguns testes.

Abaixo deixo algumas observações

Teoricamente [aqui ](https://github.com/thiagosantos/bradesco-cnab240/blob/b5740e8d8d3a33663ca40bb39bb8e09c97f2e596/exec.py#L45) é onde o uso os dados do arquivo de configuração para preencher os dados do header, incluindo o código do banco. Qual campo que ficou como o padrão? Pode ter algum erro de typo no conf e no dict padrão, ou mesmo campos que não estejam no conf padrão.
>Então, tem que parametrizar mais, algumas configurações dos headers estão hard coded, teria que pegar as informações do arquivo de configuração e colocar nas funções de header pra puxar o código do banco correto.

No header do lote não tem bairro mesmo, mas as posições deveriam ser as mesmas e no final ter 240 caracteres a linha (incluindo espaços)
>Outra diferença que notei é que no header do lote, o endereço que eles colocam não tem bairro, o que deixa a linha mais curta.

Esse campo é um campo de retorno, o banco depois que paga preenche e manda de volta pra você com a data que realmente pagou, ai por isso que na ida vai vazio

> Também nessa linha, posição 155 eles colocam a data do pagamento, o que no seu programa está 0000000000
>0770001300001A0000000770000190000006501601 NOME COLABORADOR 10032017BRL000000000000000000000000000100 10032017000000000000100 0

**Comment by gusleig** [comment]
Sakei, pois é, me parece tranquilo de fazer funcionar. As vezes esses bancos não seguem a risca o documento de especificação, por exemplo eles preencherem essa data que seria apenas preenchida no retorno me parece estranho.
Outra diferença ai é no header do lote, tinha que bater, vou fuçar aqui pra ver se tem diferença.
Vou fazer o seguinte, modificar o arquivo na mão e tentar fazer funcionar na minha conta.
Eu posso também modificar o código, mas acho melhor ter certeza que o arquivo está ok antes de sair mexendo. 
Essas modificações pra parametrizar dados do banco acho super válido, e vai ser útil até pra incluir outros bancos.
Teu programa ficou super prático e funcional, parabéns.

**Comment by thiagosantos** [comment]
Me manda o header de lote que saiu no seu arquivo de remessa?
Fiz algumas alterações agora, você pode dar um pull ai?


Essa foi a comparação que fiz aqui.

> 23700011C3001045 231886245000191328214              0027980000000085642 XXXXXXXXXXXXXXXXXXXXXX                                                XXXXXXXXXXXXXX                211                 RIO DE JANEIRO      20510010RJ01                
> 07700011C3001020 200416968000101                    0000190000003682013 BANCO INTERMEDIUM S/A                                                 AVENIDA DO CONTORNO           07777               BELO HORIZONTE      30110051MG                  
>

**Comment by gusleig** [comment]
Enviei pra você por email um arquivo que consegui fazer funcionar na minha conta PJ do banco Inter.

**Comment by thiagosantos** [comment]
Você estava certo com o header do lote. Não tem bairro, eu estava forçando, o que estava levando o nome da cidade a ser menor, e o campo do cep a ser menor ainda.

Ajustei isso e a questão da densidade que comentei no e-mail também está do no arquivo de configuração. Aproveitei e já subi dois confs padrão um do Banco Inter e outro do Bradesco.

No TXT que você me mandou por e-mail vi que você preencheu o campo da data do pagamento efetivo, mas ainda estou com o pé atrás sobre o preenchimento desse campo. Na descrição do doc de layout do Bradesco diz que deve ser preenchido quando o "código" que fica no header do arquivo for igual 2 (retorno), mas quando nós geramos, geramos como 1 (remessa) [G015]. Será esse preenchimento uma particularidade do Banco Inter?

**Comment by gusleig** [comment]
Thiago, ficou show o script.

Então, a questão do bairro o Inter aceitou mesmo mesmo com, mas realmente
não tem e é bom tirar mesmo.

Sobre as datas, pode ser uma particularidade do Inter, mas realmente se
colocar 00000000 ele não aceita.

De qualquer forma, acredito que já estamos bem avançados, o programa está
genial, me quebrou um galho enorme.

Te agradeço e acredito que vai ajudar bastante gente!


abraço


*Gustavo Leig*
Mobile: +55 21 981160777
Office: +55 21 21049592
www.gusleig.com  <http://www.gusleig.com/sos/>


Em ter., 29 de set. de 2020 às 14:50, Thiago Santos Pereira <
notifications@github.com> escreveu:

**Comment by thiagosantos** [comment]
Se isso for mesmo uma particularidade do Banco Inter vou precisar adicionar mais um campo no conf pra permitir um valor replicar o valor da data do pagamento, ou no csv adicionar mais um campo só para essa informação.

Fico feliz que o script tenha ajudado!

Espero também que o seu teste funcione e o dinheiro caía certinho na sua conta!

**Comment by thiagosantos** [comment]
@gusleig o teste que você fez funcionou?
posso fechar esse issue?

**Comment by gusleig** [comment]
Funcionou sim. Tudo ok. Consegui mandar o arquivo no Inter e realizar os pagamentos! Obrigado

**Comment by thiagosantos** [comment]
Perfeito!
Obrigado pelo feedback.
