### ISSUE TITLE
Banco Inter

### ISSUE THREAD

**Issue by BrennoCaldato** [thiagosantos/bradesco-cnab240#4]
Bom dia,

Estou tendo problema ao carregar o arquivo no banco inter. Tentei inclusive com o pull request aberto.

Os erros são:
"Conta de crédito invalida!"
"CPF xxxx invalido para a conta xxxx"

Confirmei os dados de cpf e conta diversas vezes no arquivo .csv

Alguem consegue reproduzir esse problema?

**Comment by thiagosantos** [comment]
Bom dia Brenno,

Isso acontece com uma pessoa específica ou com todos do csv?
É pagamento de Inter para Inter?

Abraço,

**Comment by BrennoCaldato** [comment]
Nao é de inter para inter. Acho que ai está o problema

**Comment by thiagosantos** [comment]
Em teoria não teria problema por que no arquivo [csv](https://github.com/thiagosantos/bradesco-cnab240/blob/master/tmp/funcionarios.csv) você define o código do banco na primeira coluna. 

No exemplo é do CSV é o 237 que é Bradesco, mas poderia ser 341 (Itaú) ou mesmo 077 (Banco Inter).

Você consegue fazer o teste para você mesmo, em uma conta diferente do Inter, fazendo um pagamento de 1 real?

**Comment by BrennoCaldato** [comment]
eu tentei fazer o pagamento para uma conta minha diferente mas não funcionou. alterei o numero do banco corretamente. 
Falando com o suporte parece que é bloqueado somente para contas do banco, infelizmente

**Comment by thiagosantos** [comment]
Que mais coisa chata e uma pena!
Inúmeras possibilidades perdidas com esse bloqueio.

Fico feliz que pelo menos você conseguiu usar o projeto.

Abraço
