### ISSUE TITLE
Arquivo .REM

### ISSUE THREAD

**Issue by jessicaevelin** [thiagosantos/bradesco-cnab240#5]
Oi, boa tarde
Eu consegui rodar o código e está funcionando direitinho, só que o banco inter pede que o arquivo esteja no formato .REM e o código está gerando um .txt.
Pode me ajudar?

**Comment by thiagosantos** [comment]
Olá Jessica!
O banco inter precisa que a extensão seja .REM ou REM é um formato?

Se for só a extensão eu consigo adicionar um parametro adicional onde você passaria o nome do arquivo de saída. Daí você conseguiria pôr qualquer nome no arquivo de saída.

Att.,

**Comment by rafao13** [comment]
Boa tarde, aqui eu uso o INTER e importo ele .txt mesmo. Não tenho problemas, será que esta tentando importar por outra tela/ outro metodo ?

**Comment by jessicaevelin** [comment]
Oi, eu consegui resolver.
Entrei em contato com o suporte do Banco Inter e pedi ajuda, eles me enviaram um .xlsx padrão deles que faz esse pagamento e também percebi que o o master da conta não tinha me liberado o acesso 🤪.
Aí o seu código funcionou e a planilha do Inter também.
Obrigada por disponibilizar
